libraryproject/books/urls.py
from django.urls import path

from books import views

app_name = "books"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:book_id>/", views.details, name="details"),
    path("authors/", views.authors, name="authors"),
    path("authors/<int:author_id>/", views.authors_details, name="authors_details"),
    path("authors/add_author/", views.add_author, name="add_author"),
    path("authors/add_authors/", views.add_authors, name="add_authors"),
]

libraryproject/libraryproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include("books.urls")),
]

libraryproject/books/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField(blank=True, null=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ManyToManyField(Author, related_name='books')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    publish_date = models.DateField()
    summary = models.TextField()

    def __str__(self):
        return f'{self.title}'

libraryproject/books/views.py
from django.urls import reverse

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from books.models import Book, Author


# Create your views here.

def index(request):
    books_list = Book.objects.all()
    context = {
        'books_list': books_list
    }
    return render(request, "books/index.html", context)

def details(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, "books/details.html", {'book': book})

def authors(request):
    authors = Author.objects.all()
    context = {
        'authors': authors
    }
    return render(request, "books/authors.html", context)

def authors_details(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    books_list = author.books.all()
    return render(request, "books/authors_details.html", {'author': author, 'books_list': books_list})

def add_author(request):
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        birth_date = request.POST['birth_date']
        Author.objects.create(first_name=first_name, last_name=last_name, birth_date=birth_date)
        return HttpResponseRedirect(reverse("books:authors"))

def add_authors(request):
    return render(request, "books/add_authors.html")

libraryproject/books/templates/books/add_authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Añadir Authors</title>
</head>
<body>
    <form method="post" action="{% url "books:add_author" %}">
        {% csrf_token %}
        <label for="first_name">Nombre:</label>
        <input type="text" id="first_name" name="first_name" required>
        <label for="last_name">Apellidos:</label>
        <input type="text" id="last_name" name="last_name" required>
        <label for="birth_date">Fecha de Nacimiento:</label>
        <input type="date" id="birth_date" name="birth_date">
        <input type="submit" value="Agregar" >
    </form>
</body>
</html>

libraryproject/books/templates/books/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
<p>Si quieres añadir nuevos autores <a href="{% url 'books:add_authors' %}">pincha aquí</a></p>
    {% if authors %}
        <ul>
        {% for author in authors %}
            <li><a href="{% url 'books:authors_details' author.id %}">{{ author.first_name }} {{ author.last_name }}  
            </a></li> {% endfor %}
        </ul>
    {% else %}
        <p>No Authors are available.</p>
    {% endif %}
</body>
</html>

libraryproject/books/templates/books/authors_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DetallesAutor</title>
</head>
<body>
    <h1>Detalles del Autor</h1>
    <h2>Nombre Completo</h2>
        <h3>{{ author.first_name }} {{ author.last_name }}</h3>
    <h2>Fecha de nacimiento</h2>
        <h3>{{ author.birth_date }}</h3>
    <h2>Libros publicados</h2>
    <ul>
        {% for book in books_list %}
    	    <li>{{ book.title }}</li>
        {% endfor %}  
    </ul>
</body>
</html>

libraryproject/books/templates/books/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DetallesLibro</title>
</head>
<body>
    <h1>Detalles del libro</h1>
    <h2> {{ book.title }}</h2>
    <h2>Author</h2>
    <ul>
        {% for author in book.author.all %}
    	    <li>{{ author }}</li>
        {% endfor %}  
    </ul>
    <h2>Genre</h2>
    <h3>{{ book.genre }}</h3>
    <h2>Publish Date</h2>
    <h3>{{ book.publish_date }}</h3>
    <h2>Summary</h2>
    <p>{{ book.summary }}</p>
</body>
</html>

libraryproject/books/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PáginaPrincipal</title>
</head>
<body>
    {% if books_list %}
        <ul>
        {% for book in books_list %}
            <li><a href="{% url 'books:details' book.id %}">{{ book.title }}:
                {% for author in book.author.all %}
                    {{ author }}
                {% endfor %}
            </a></li> {% endfor %}
        </ul>
    {% else %}
        <p>No books are available.</p>
    {% endif %}
</body>
</html>